/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\my-blog\\my-blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-cd6ab84c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cd6ab84c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-2ee65f8a",
    path: "/blogs/electron/electron%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86%EF%BC%88%E4%B8%80%EF%BC%89.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ee65f8a").then(next)
    },
  },
  {
    path: "/blogs/electron/electron基础知识（一）.html",
    redirect: "/blogs/electron/electron%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86%EF%BC%88%E4%B8%80%EF%BC%89.html"
  },
  {
    path: "/blogs/electron/electron基础知识（一）.html",
    redirect: "/blogs/electron/electron%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86%EF%BC%88%E4%B8%80%EF%BC%89.html"
  },
  {
    name: "v-82973ee6",
    path: "/blogs/electron/electron%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86%EF%BC%88%E4%B8%89%EF%BC%89.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-82973ee6").then(next)
    },
  },
  {
    path: "/blogs/electron/electron基础知识（三）.html",
    redirect: "/blogs/electron/electron%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86%EF%BC%88%E4%B8%89%EF%BC%89.html"
  },
  {
    path: "/blogs/electron/electron基础知识（三）.html",
    redirect: "/blogs/electron/electron%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86%EF%BC%88%E4%B8%89%EF%BC%89.html"
  },
  {
    name: "v-663e6e13",
    path: "/blogs/javascript/javaScript%E6%A0%87%E7%AD%BE%E4%BD%BF%E7%94%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-663e6e13").then(next)
    },
  },
  {
    path: "/blogs/javascript/javaScript标签使用.html",
    redirect: "/blogs/javascript/javaScript%E6%A0%87%E7%AD%BE%E4%BD%BF%E7%94%A8.html"
  },
  {
    path: "/blogs/javascript/javaScript标签使用.html",
    redirect: "/blogs/javascript/javaScript%E6%A0%87%E7%AD%BE%E4%BD%BF%E7%94%A8.html"
  },
  {
    name: "v-d5b1d29e",
    path: "/blogs/electron/electron%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86%EF%BC%88%E4%BA%8C%EF%BC%89.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d5b1d29e").then(next)
    },
  },
  {
    path: "/blogs/electron/electron基础知识（二）.html",
    redirect: "/blogs/electron/electron%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86%EF%BC%88%E4%BA%8C%EF%BC%89.html"
  },
  {
    path: "/blogs/electron/electron基础知识（二）.html",
    redirect: "/blogs/electron/electron%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86%EF%BC%88%E4%BA%8C%EF%BC%89.html"
  },
  {
    name: "v-47667b1a",
    path: "/blogs/react/normalizr%E4%BD%BF%E7%94%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47667b1a").then(next)
    },
  },
  {
    path: "/blogs/react/normalizr使用.html",
    redirect: "/blogs/react/normalizr%E4%BD%BF%E7%94%A8.html"
  },
  {
    path: "/blogs/react/normalizr使用.html",
    redirect: "/blogs/react/normalizr%E4%BD%BF%E7%94%A8.html"
  },
  {
    name: "v-4879d214",
    path: "/blogs/react/redux%E6%BA%90%E7%A0%81%E8%AF%A6%E8%A7%A3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4879d214").then(next)
    },
  },
  {
    path: "/blogs/react/redux源码详解.html",
    redirect: "/blogs/react/redux%E6%BA%90%E7%A0%81%E8%AF%A6%E8%A7%A3.html"
  },
  {
    path: "/blogs/react/redux源码详解.html",
    redirect: "/blogs/react/redux%E6%BA%90%E7%A0%81%E8%AF%A6%E8%A7%A3.html"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-7213ab03",
    path: "/tag/Electron/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-7213ab03").then(next)
    },
    meta: {"pid":"tags","id":"Electron"}
  },
  {
    path: "/tag/Electron/index.html",
    redirect: "/tag/Electron/"
  },
  {
    name: "v-5f66a358",
    path: "/tag/javaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-5f66a358").then(next)
    },
    meta: {"pid":"tags","id":"javaScript"}
  },
  {
    path: "/tag/javaScript/index.html",
    redirect: "/tag/javaScript/"
  },
  {
    name: "v-38c6db02",
    path: "/tag/normalizr/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-38c6db02").then(next)
    },
    meta: {"pid":"tags","id":"normalizr"}
  },
  {
    path: "/tag/normalizr/index.html",
    redirect: "/tag/normalizr/"
  },
  {
    name: "v-6018aa36",
    path: "/tag/redux/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-6018aa36").then(next)
    },
    meta: {"pid":"tags","id":"redux"}
  },
  {
    path: "/tag/redux/index.html",
    redirect: "/tag/redux/"
  },
  {
    name: "v-dbc4c9e2",
    path: "/categories/Electron/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-dbc4c9e2").then(next)
    },
    meta: {"pid":"categories","id":"Electron"}
  },
  {
    path: "/categories/Electron/index.html",
    redirect: "/categories/Electron/"
  },
  {
    name: "v-b6967f38",
    path: "/categories/javaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-b6967f38").then(next)
    },
    meta: {"pid":"categories","id":"javaScript"}
  },
  {
    path: "/categories/javaScript/index.html",
    redirect: "/categories/javaScript/"
  },
  {
    name: "v-977a34f0",
    path: "/categories/react 相关/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-977a34f0").then(next)
    },
    meta: {"pid":"categories","id":"react 相关"}
  },
  {
    path: "/categories/react 相关/index.html",
    redirect: "/categories/react 相关/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]