/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "RuyWan-blog",
  "description": "my-blog",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": " ",
        "tagline": " ",
        "heroImageStyle": {
          "maxWidth": "600px",
          "width": "100%",
          "display": "block",
          "margin": "9rem auto 2rem",
          "background": "#D6E5FC",
          "borderRadius": "1rem"
        },
        "bgImageStyle": {
          "height": "550px",
          "background-image": "url('/map.jpeg')"
        },
        "isShowTitleInHome": false,
        "actionText": "Guide",
        "actionLink": "/views/other/guide",
        "features": [
          {
            "title": "Yesterday",
            "details": "开发一款看着开心、写着顺手的 vuepress 博客主题"
          },
          {
            "title": "Today",
            "details": "希望帮助更多的人花更多的时间在内容创作上，而不是博客搭建上"
          },
          {
            "title": "Tomorrow",
            "details": "希望更多的爱好者能够参与进来，帮助这个主题更好的成长"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-cd6ab84c",
      "path": "/",
      "lastUpdated": "1/12/2023, 10:42:04 AM",
      "lastUpdatedTimestamp": 1673491324000
    },
    {
      "title": "Electron 基础知识（一)",
      "frontmatter": {
        "title": "Electron 基础知识（一)",
        "date": "2023-1-24",
        "sidebar": "auto",
        "categories": [
          "Electron"
        ],
        "tags": [
          "Electron"
        ]
      },
      "regularPath": "/blogs/electron/electron%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86%EF%BC%88%E4%B8%80%EF%BC%89.html",
      "relativePath": "blogs/electron/electron基础知识（一）.md",
      "key": "v-2ee65f8a",
      "path": "/blogs/electron/electron%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86%EF%BC%88%E4%B8%80%EF%BC%89.html",
      "headers": [
        {
          "level": 2,
          "title": "初始化Electron",
          "slug": "初始化electron"
        },
        {
          "level": 2,
          "title": "main指向文件引用electron",
          "slug": "main指向文件引用electron"
        },
        {
          "level": 2,
          "title": "安装electron 热加载工具",
          "slug": "安装electron-热加载工具"
        },
        {
          "level": 2,
          "title": "打开页面调试",
          "slug": "打开页面调试"
        },
        {
          "level": 2,
          "title": "electron 常用生命周期",
          "slug": "electron-常用生命周期"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>如果你可以建一个网站，你就可以建一个桌面应用程序。Electron是一个使用javaScript,HTML和Css等Web技术创建原生程序的框架，它负责把你的页面部分打包成跨平台的（Windows,Mac,Linux）应用程序，而开发者可以把精力放到应用的核心功能实现即可。\n本篇记录一些基础的运用，帮你打开一个Hello Electron!</p>\n</div>",
      "lastUpdated": "2/2/2023, 10:39:32 PM",
      "lastUpdatedTimestamp": 1675348772000
    },
    {
      "title": "Electron 基础知识（三)",
      "frontmatter": {
        "title": "Electron 基础知识（三)",
        "date": "2023-1-26",
        "sidebar": "auto",
        "categories": [
          "Electron"
        ],
        "tags": [
          "Electron"
        ]
      },
      "regularPath": "/blogs/electron/electron%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86%EF%BC%88%E4%B8%89%EF%BC%89.html",
      "relativePath": "blogs/electron/electron基础知识（三）.md",
      "key": "v-82973ee6",
      "path": "/blogs/electron/electron%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86%EF%BC%88%E4%B8%89%EF%BC%89.html",
      "headers": [
        {
          "level": 2,
          "title": "窗口区分",
          "slug": "窗口区分"
        },
        {
          "level": 2,
          "title": "自定义右键菜单",
          "slug": "自定义右键菜单"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>本篇记录各个窗口及自定义右键的使用!</p>\n</div>",
      "lastUpdated": "2/2/2023, 10:39:32 PM",
      "lastUpdatedTimestamp": 1675348772000
    },
    {
      "title": "javaScript 标签使用",
      "frontmatter": {
        "title": "javaScript 标签使用",
        "date": "2023-1-14",
        "sidebar": "auto",
        "categories": [
          "javaScript"
        ],
        "tags": [
          "javaScript"
        ]
      },
      "regularPath": "/blogs/javascript/javaScript%E6%A0%87%E7%AD%BE%E4%BD%BF%E7%94%A8.html",
      "relativePath": "blogs/javascript/javaScript标签使用.md",
      "key": "v-663e6e13",
      "path": "/blogs/javascript/javaScript%E6%A0%87%E7%AD%BE%E4%BD%BF%E7%94%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "javaScript元素标签常用属性",
          "slug": "javascript元素标签常用属性"
        },
        {
          "level": 3,
          "title": "正常情况下的执行顺序",
          "slug": "正常情况下的执行顺序"
        },
        {
          "level": 3,
          "title": "async属性",
          "slug": "async属性"
        },
        {
          "level": 3,
          "title": "defer属性",
          "slug": "defer属性"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>在Html页面中，我们会引入外部js，但是这些js文件是有执行顺序的，我们需要对此有一定的了解，在引用js文件时确定其执行顺序</p>\n</div>",
      "lastUpdated": "1/14/2023, 11:00:09 PM",
      "lastUpdatedTimestamp": 1673708409000
    },
    {
      "title": "Electron 基础知识（二)",
      "frontmatter": {
        "title": "Electron 基础知识（二)",
        "date": "2023-1-25",
        "sidebar": "auto",
        "categories": [
          "Electron"
        ],
        "tags": [
          "Electron"
        ]
      },
      "regularPath": "/blogs/electron/electron%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86%EF%BC%88%E4%BA%8C%EF%BC%89.html",
      "relativePath": "blogs/electron/electron基础知识（二）.md",
      "key": "v-d5b1d29e",
      "path": "/blogs/electron/electron%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86%EF%BC%88%E4%BA%8C%EF%BC%89.html",
      "headers": [
        {
          "level": 2,
          "title": "原生窗口菜单的使用",
          "slug": "原生窗口菜单的使用"
        },
        {
          "level": 3,
          "title": "修改默认菜单及添加子菜单",
          "slug": "修改默认菜单及添加子菜单"
        },
        {
          "level": 3,
          "title": "菜单类型,内容区分",
          "slug": "菜单类型-内容区分"
        },
        {
          "level": 3,
          "title": "窗口配置",
          "slug": "窗口配置"
        },
        {
          "level": 3,
          "title": "自定义窗口菜单编写",
          "slug": "自定义窗口菜单编写"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>本篇记录窗口菜单的使用及如何自定义窗口!</p>\n</div>",
      "lastUpdated": "2/2/2023, 10:39:32 PM",
      "lastUpdatedTimestamp": 1675348772000
    },
    {
      "title": "normalizr使用",
      "frontmatter": {
        "title": "normalizr使用",
        "date": "2022-10-24",
        "sidebar": "auto",
        "categories": [
          "react 相关"
        ],
        "tags": [
          "normalizr"
        ]
      },
      "regularPath": "/blogs/react/normalizr%E4%BD%BF%E7%94%A8.html",
      "relativePath": "blogs/react/normalizr使用.md",
      "key": "v-47667b1a",
      "path": "/blogs/react/normalizr%E4%BD%BF%E7%94%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "normalizr简介",
          "slug": "normalizr简介"
        },
        {
          "level": 2,
          "title": "normalizr安装",
          "slug": "normalizr安装"
        },
        {
          "level": 2,
          "title": "normalizr使用",
          "slug": "normalizr使用"
        },
        {
          "level": 2,
          "title": "schema其他参数使用",
          "slug": "schema其他参数使用"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>项目中经常会遇到后端给出的数据结构，不满足前端渲染所需要的数据结构，这时就需要对数据进行处理改造，变成符合前端需要的数据格式及结构，这时，就需要用要normalizr来进行数据处理</p>\n</div>",
      "lastUpdated": "1/14/2023, 11:00:09 PM",
      "lastUpdatedTimestamp": 1673708409000
    },
    {
      "title": "redux源码详解",
      "frontmatter": {
        "title": "redux源码详解",
        "date": "2022-11-1",
        "sidebar": "auto",
        "categories": [
          "react 相关"
        ],
        "tags": [
          "redux"
        ]
      },
      "regularPath": "/blogs/react/redux%E6%BA%90%E7%A0%81%E8%AF%A6%E8%A7%A3.html",
      "relativePath": "blogs/react/redux源码详解.md",
      "key": "v-4879d214",
      "path": "/blogs/react/redux%E6%BA%90%E7%A0%81%E8%AF%A6%E8%A7%A3.html",
      "headers": [
        {
          "level": 2,
          "title": "createStore文件详细解析",
          "slug": "createstore文件详细解析"
        }
      ],
      "excerpt": "<div class=\"custom-block tip\"><p class=\"title\"></p><p>redux是js应用的状态容器，提供可预测的状态管理。在react的开发体系中，redux占据了非常重要的位置。\n官网链接：https://cn.redux.js.org/</p>\n</div>",
      "lastUpdated": "1/14/2023, 11:00:09 PM",
      "lastUpdatedTimestamp": 1673708409000
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Electron Tags"
      },
      "regularPath": "/tag/Electron/",
      "key": "v-7213ab03",
      "path": "/tag/Electron/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "javaScript Tags"
      },
      "regularPath": "/tag/javaScript/",
      "key": "v-5f66a358",
      "path": "/tag/javaScript/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "normalizr Tags"
      },
      "regularPath": "/tag/normalizr/",
      "key": "v-38c6db02",
      "path": "/tag/normalizr/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "redux Tags"
      },
      "regularPath": "/tag/redux/",
      "key": "v-6018aa36",
      "path": "/tag/redux/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Electron Categories"
      },
      "regularPath": "/categories/Electron/",
      "key": "v-dbc4c9e2",
      "path": "/categories/Electron/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "javaScript Categories"
      },
      "regularPath": "/categories/javaScript/",
      "key": "v-b6967f38",
      "path": "/categories/javaScript/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "react 相关 Categories"
      },
      "regularPath": "/categories/react%20%E7%9B%B8%E5%85%B3/",
      "key": "v-977a34f0",
      "path": "/categories/react 相关/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "Home",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "TimeLine",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "Contact",
        "icon": "reco-message",
        "items": [
          {
            "text": "GitHub",
            "link": "https://github.com/recoluan",
            "icon": "reco-github"
          }
        ]
      }
    ],
    "sidebar": {
      "/docs/theme-reco/": [
        "",
        "theme",
        "plugin",
        "api"
      ]
    },
    "type": "blog",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "Category"
      },
      "tag": {
        "location": 3,
        "text": "Tag"
      }
    },
    "friendLink": [
      {
        "title": "vuepress-theme-reco",
        "desc": "A simple and beautiful vuepress Blog & Doc theme.",
        "avatar": "https://vuepress-theme-reco.recoluan.com/icon_vuepress_reco.png",
        "link": "https://vuepress-theme-reco.recoluan.com"
      }
    ],
    "logo": "/autor.jpeg",
    "search": true,
    "searchMaxSuggestions": 10,
    "lastUpdated": "Last Updated",
    "author": "wanliang",
    "authorAvatar": "/autor.jpeg",
    "startYear": "2022"
  }
}