/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "Electron": {
      "key": "Electron",
      "scope": "tags",
      "path": "/tag/Electron/",
      "pageKeys": [
        "v-56a93afd",
        "v-521d7f87"
      ]
    },
    "javaScript": {
      "key": "javaScript",
      "scope": "tags",
      "path": "/tag/javaScript/",
      "pageKeys": [
        "v-663e6e13"
      ]
    },
    "normalizr": {
      "key": "normalizr",
      "scope": "tags",
      "path": "/tag/normalizr/",
      "pageKeys": [
        "v-47667b1a"
      ]
    },
    "redux": {
      "key": "redux",
      "scope": "tags",
      "path": "/tag/redux/",
      "pageKeys": [
        "v-4879d214"
      ]
    }
  },
  "categories": {
    "Electron": {
      "key": "Electron",
      "scope": "categories",
      "path": "/categories/Electron/",
      "pageKeys": [
        "v-56a93afd",
        "v-521d7f87"
      ]
    },
    "javaScript": {
      "key": "javaScript",
      "scope": "categories",
      "path": "/categories/javaScript/",
      "pageKeys": [
        "v-663e6e13"
      ]
    },
    "react 相关": {
      "key": "react 相关",
      "scope": "categories",
      "path": "/categories/react 相关/",
      "pageKeys": [
        "v-47667b1a",
        "v-4879d214"
      ]
    }
  },
  "timeline": {}
}