/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "Electron",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/Electron/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "javaScript",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/javaScript/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "normalizr",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/normalizr/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "redux",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/redux/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "Electron",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/Electron/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "javaScript",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/javaScript/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "react 相关",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/react 相关/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
}]